<a href="https://colab.research.google.com/github/keshavsoliwal911-netizen/House_price_prediction/blob/main/Housepriceprdeiction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
house = pd.read_csv('housing.csv')
house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND


In [ ]:
X = house.drop(['median_house_value'], axis=1)
y = house['median_house_value']

In [ ]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND


In [ ]:
y

,median_house_value
0,452600.0
1,358500.0
2,352100.0
3,341300.0
4,342200.0
...,...
20635,78100.0
20636,77100.0
20637,92300.0
20638,84700.0


In [ ]:
np.corrcoef(X['median_income'], y)

array([[1.        , 0.68807521],
       [0.68807521, 1.        ]])

In [ ]:
np.corrcoef(X['median_income'], y)[0,1]


np.float64(0.688075207958548)

In [ ]:
for i in X:
    if i == 'ocean_proximity':
        continue
    print(f"Feature name: {i}")
    r = np.corrcoef(X[i], y)[0,1]
    print(f"correlation: {r}")
    print()


Feature name: longitude
correlation: -0.0459666151179785

Feature name: latitude
correlation: -0.1441602768746594

Feature name: housing_median_age
correlation: 0.10562341249320996

Feature name: total_rooms
correlation: 0.1341531138065631

Feature name: total_bedrooms
correlation: nan

Feature name: population
correlation: -0.02464967888889488

Feature name: households
correlation: 0.06584265057005648

Feature name: median_income
correlation: 0.688075207958548



In [ ]:
new_feature = X['latitude'] + X['longitude']
new_feature

,0
0,-84.35
1,-84.36
2,-84.39
3,-84.40
4,-84.40
...,...
20635,-81.61
20636,-81.72
20637,-81.79
20638,-81.89


In [ ]:
np.corrcoef(new_feature, y)

array([[ 1.        , -0.49151968],
       [-0.49151968,  1.        ]])

In [ ]:
X.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY


In [ ]:
y.head()

,median_house_value
0,452600.0
1,358500.0
2,352100.0
3,341300.0
4,342200.0


In [ ]:
X.shape

(20640, 9)

In [ ]:
size = X.shape[0]
size

20640

In [ ]:
test_size = 0.2

In [ ]:
testing_size = int(size * 0.2)
testing_size

4128

In [ ]:
training_size = size - testing_size
training_size

16512

In [ ]:
X.iloc[:training_size]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
16507,-121.11,37.74,11.0,3886.0,599.0,1605.0,529.0,4.4213,INLAND
16508,-121.10,37.80,35.0,1853.0,331.0,958.0,340.0,3.3578,INLAND
16509,-121.11,37.76,22.0,2606.0,411.0,1252.0,397.0,4.1833,INLAND
16510,-121.16,37.73,7.0,4956.0,941.0,3006.0,915.0,3.4426,INLAND


In [ ]:
X.iloc[training_size:]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16512,-121.22,37.72,34.0,2123.0,387.0,1310.0,368.0,2.6368,INLAND
16513,-121.22,37.81,17.0,2879.0,542.0,1802.0,530.0,3.6378,INLAND
16514,-121.22,37.80,28.0,2608.0,576.0,1719.0,554.0,2.1186,INLAND
16515,-121.22,37.80,37.0,1038.0,222.0,521.0,211.0,2.1250,INLAND
16516,-121.21,37.81,18.0,2404.0,498.0,1531.0,506.0,2.9950,INLAND
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND


In [ ]:
X = house.drop(['median_house_value'], axis=1)
y = house['median_house_value']

In [ ]:
def train_test_split(X, y, test_size=0.2):
    size = X.shape[0]
    testing_size = int(size * test_size)
    training_size = size - testing_size

    train_X = X.iloc[:training_size]
    test_X = X.iloc[training_size:]

    train_y = y.iloc[:training_size]
    test_y = y.iloc[training_size:]

    return train_X, test_X, train_y, test_y



In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
16507,-121.11,37.74,11.0,3886.0,599.0,1605.0,529.0,4.4213,INLAND
16508,-121.10,37.80,35.0,1853.0,331.0,958.0,340.0,3.3578,INLAND
16509,-121.11,37.76,22.0,2606.0,411.0,1252.0,397.0,4.1833,INLAND
16510,-121.16,37.73,7.0,4956.0,941.0,3006.0,915.0,3.4426,INLAND


In [ ]:
y_train

,median_house_value
0,452600.0
1,358500.0
2,352100.0
3,341300.0
4,342200.0
...,...
16507,182700.0
16508,149000.0
16509,192100.0
16510,139000.0


In [ ]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16512,-121.22,37.72,34.0,2123.0,387.0,1310.0,368.0,2.6368,INLAND
16513,-121.22,37.81,17.0,2879.0,542.0,1802.0,530.0,3.6378,INLAND
16514,-121.22,37.80,28.0,2608.0,576.0,1719.0,554.0,2.1186,INLAND
16515,-121.22,37.80,37.0,1038.0,222.0,521.0,211.0,2.1250,INLAND
16516,-121.21,37.81,18.0,2404.0,498.0,1531.0,506.0,2.9950,INLAND
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND


In [ ]:
y_test

,median_house_value
16512,165600.0
16513,126100.0
16514,94400.0
16515,91900.0
16516,124300.0
...,...
20635,78100.0
20636,77100.0
20637,92300.0
20638,84700.0


In [ ]:
l = [10,20,30,40,50,60,70,80]

In [ ]:
np.random.shuffle(l)
l

[10, 80, 30, 70, 40, 60, 50, 20]

In [ ]:
size
indexes = np.arange(size)
indexes

array([    0,     1,     2, ..., 20637, 20638, 20639])

In [ ]:
np.random.shuffle(indexes)

In [ ]:
indexes

array([ 1619, 15907, 10132, ...,  7943, 13780, 14661])

In [ ]:
def train_test_split(X, y, test_size=0.2):
    np.random.seed(123)
    size = X.shape[0]
    indexes = np.arange(size)
    np.random.shuffle(indexes)

    testing_size = int(size * test_size)
    training_size = size - testing_size

    train_idx = indexes[:training_size]
    test_idx = indexes[training_size:]

    train_X = X.iloc[train_idx]
    test_X = X.iloc[test_idx]
    train_y = y.iloc[train_idx]
    test_y = y.iloc[test_idx]

    return train_X, test_X, train_y, test_y




In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [ ]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
19121,-122.64,38.24,40.0,1974.0,410.0,1039.0,398.0,3.7917,<1H OCEAN
20019,-119.05,36.09,9.0,3297.0,568.0,1749.0,568.0,4.0217,INLAND
15104,-116.98,32.85,12.0,3570.0,713.0,3321.0,666.0,4.0882,<1H OCEAN
3720,-118.42,34.20,27.0,3201.0,970.0,3403.0,948.0,2.2377,<1H OCEAN
8938,-118.47,34.01,41.0,2704.0,557.0,1047.0,478.0,4.4211,<1H OCEAN


In [ ]:
y_train.head()

,median_house_value
19121,151600.0
20019,99200.0
15104,134500.0
3720,231700.0
8938,462900.0


In [ ]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
19121,-122.64,38.24,40.0,1974.0,410.0,1039.0,398.0,3.7917,<1H OCEAN
20019,-119.05,36.09,9.0,3297.0,568.0,1749.0,568.0,4.0217,INLAND
15104,-116.98,32.85,12.0,3570.0,713.0,3321.0,666.0,4.0882,<1H OCEAN
3720,-118.42,34.20,27.0,3201.0,970.0,3403.0,948.0,2.2377,<1H OCEAN
8938,-118.47,34.01,41.0,2704.0,557.0,1047.0,478.0,4.4211,<1H OCEAN


In [ ]:
X_train['ocean_proximity'].value_counts() / X_train.shape[0] * 100

,count
ocean_proximity,
<1H OCEAN,44.295058
INLAND,31.801114
NEAR OCEAN,12.645349
NEAR BAY,11.234254
ISLAND,0.024225


In [ ]:
X_test['ocean_proximity'].value_counts() / X_test.shape[0] * 100


,count
ocean_proximity,
<1H OCEAN,44.137597
INLAND,31.492248
NEAR OCEAN,13.808140
NEAR BAY,10.537791
ISLAND,0.024225


In [ ]:
l

[10, 80, 30, 70, 40, 60, 50, 20]

In [ ]:
l = [1,2,3,4,5,6,7,8,9,10]
np.random.seed(123)
np.random.shuffle(l)
l

[5, 1, 8, 6, 9, 4, 2, 7, 10, 3]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=123)

In [ ]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
9950,-122.33,38.38,28.0,1020.0,169.0,504.0,164.0,4.5694,INLAND
3547,-118.60,34.26,18.0,6154.0,1070.0,3010.0,1034.0,5.6392,<1H OCEAN
4448,-118.21,34.07,47.0,1346.0,383.0,1452.0,371.0,1.7292,<1H OCEAN
6984,-118.02,33.96,36.0,2071.0,398.0,988.0,404.0,4.6226,<1H OCEAN
4432,-118.20,34.08,49.0,1320.0,309.0,1405.0,328.0,2.4375,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
7763,-118.10,33.91,36.0,726.0,NaN,490.0,130.0,3.6389,<1H OCEAN
15377,-117.24,33.37,14.0,4687.0,793.0,2436.0,779.0,4.5391,<1H OCEAN
17730,-121.76,37.33,5.0,4153.0,719.0,2435.0,697.0,5.6306,<1H OCEAN
15725,-122.44,37.78,44.0,1545.0,334.0,561.0,326.0,3.8750,NEAR BAY


In [ ]:
y_train

,median_house_value
9950,287500.0
3547,271500.0
4448,191700.0
6984,219700.0
4432,114000.0
...,...
7763,167600.0
15377,180900.0
17730,286200.0
15725,412500.0


In [ ]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
19121,-122.64,38.24,40.0,1974.0,410.0,1039.0,398.0,3.7917,<1H OCEAN
20019,-119.05,36.09,9.0,3297.0,568.0,1749.0,568.0,4.0217,INLAND
15104,-116.98,32.85,12.0,3570.0,713.0,3321.0,666.0,4.0882,<1H OCEAN
3720,-118.42,34.20,27.0,3201.0,970.0,3403.0,948.0,2.2377,<1H OCEAN
8938,-118.47,34.01,41.0,2704.0,557.0,1047.0,478.0,4.4211,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
313,-122.19,37.77,45.0,1852.0,393.0,1132.0,349.0,2.7159,NEAR BAY
4596,-118.28,34.05,41.0,1788.0,774.0,2931.0,702.0,1.4413,<1H OCEAN
16287,-121.28,37.91,31.0,820.0,179.0,576.0,155.0,1.6900,INLAND
5771,-118.27,34.15,22.0,2265.0,637.0,1684.0,561.0,2.6729,<1H OCEAN
